### ISSUE TITLE
Named arguments don't support named_argument_with_underscores

### ISSUE THREAD

**Issue by scrabsha** [vstojkovic/rt-format#5]
Hello,
It turns out that the following program panics:

```rust
use std::{
    collections::HashMap,
    fmt::{self, Display, Formatter},
};

use rt_format::{FormatArgument, ParsedFormat, Specifier};

struct Variant<'a>(&'a str);

impl<'a> FormatArgument for Variant<'a> {
    fn supports_format(&self, _specifier: &Specifier) -> bool {
        true
    }

    fn fmt_display(&self, f: &mut Formatter) -> fmt::Result {
        self.0.fmt(f)
    }

    fn fmt_debug(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_octal(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_lower_hex(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_upper_hex(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_binary(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_lower_exp(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }

    fn fmt_upper_exp(&self, _f: &mut fmt::Formatter) -> fmt::Result {
        Err(fmt::Error)
    }
}

fn main() {
    let format = "Hey {user_name}!";

    let mut named = HashMap::new();
    let _ = named.insert("user_name", Variant("Grace Hopper"));

    let args = ParsedFormat::parse(format, &[], &named).unwrap();

    let left = format!("{args}");
    let right = "Hey Grace Hopper!";

    assert_eq!(left, right);
}
```

I get the following console output:

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/tmp-tripuk`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 4', src/main.rs:54:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
   4: tmp_tripuk::main
             at ./src/main.rs:54:16
   5: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

It happens at least on version `0.3.0` (commit [165b556](https://github.com/vstojkovic/rt-format/commit/165b556c866b785532f2f763490a025817f4e8e7)).

I'd love to tackle this issue by myself. Can you provide some guidance on how I could fix it?

**Comment by vstojkovic** [comment]
The problem is in my regular expression in `parser.rs`. It only recognizes named arguments that start with an alphabetic character followed by zero or more alphanumeric characters. To be in line with what Rust's `format` macro allows, it should accept named arguments that start with either an XID_Start character or an underscore, followed by zero or more XID_Continue characters.

I already have a commit ready which fixes the parser and adds a unit test for this. I can push that into the repo, or would you prefer to open your own PR for that?

**Comment by scrabsha** [comment]
Thank you for your reply and for the clarifications. It's much appreciated!

Feel free to push your commit and close the issue. By the way, can you publish a `0.3.1` release once it's done? :eyes:

**Comment by vstojkovic** [comment]
Done! Thank you for finding this bug :)
